import type { InputInfo } from '@/types/api'

export interface InputDisplayRow extends InputInfo {
  scpName: string
  sioName: string
}

export const MOCK_INPUTS: InputDisplayRow[] = [
  {
    scp: 1,
    id: 1,
    name: 'LP4502-I-SW8',
    active: 1,
    sio: 0,
    addr: 8,
    ifcode: 0,
    mode: 1,
    delayentry: 0,
    delayexit: 0,
    ext: '',
    icvt: 5,
    debounce: 0,
    holdtime: 0,
    scpName: 'KIT_LP4502',
    sioName: 'Internal',
  },
  {
    scp: 1,
    id: 2,
    name: 'LP4502-I-CR1-DOOR',
    active: 1,
    sio: 0,
    addr: 1,
    ifcode: 0,
    mode: 1,
    delayentry: 0,
    delayexit: 0,
    ext: '',
    icvt: 0,
    debounce: 0,
    holdtime: 0,
    scpName: 'KIT_LP4502',
    sioName: 'Internal',
  },
  {
    scp: 1,
    id: 3,
    name: 'LP4502-I-CR1-REX',
    active: 1,
    sio: 0,
    addr: 2,
    ifcode: 0,
    mode: 1,
    delayentry: 0,
    delayexit: 0,
    ext: '',
    icvt: 0,
    debounce: 0,
    holdtime: 0,
    scpName: 'KIT_LP4502',
    sioName: 'Internal',
  },
  {
    scp: 2,
    id: 1,
    name: 'LP1502-I-CR1-DOOR',
    active: 1,
    sio: 0,
    addr: 1,
    ifcode: 0,
    mode: 1,
    delayentry: 0,
    delayexit: 0,
    ext: '',
    icvt: 0,
    debounce: 0,
    holdtime: 0,
    scpName: 'KIT_LP1502',
    sioName: 'Internal',
  },
  {
    scp: 1,
    id: 4,
    name: 'IMR16IN-CH1',
    active: 0,
    sio: 1,
    addr: 1,
    ifcode: 0,
    mode: 0,
    delayentry: 0,
    delayexit: 0,
    ext: '',
    icvt: 0,
    debounce: 0,
    holdtime: 2,
    scpName: 'KIT_LP4502',
    sioName: 'IMR16IN',
  },
]

export const inputRowKey = (row: Pick<InputInfo, 'scp' | 'id'>): string => `${row.scp}:${row.id}`

export const inputGridId = (row: Pick<InputInfo, 'scp' | 'id'>): number =>
  row.scp * 100000 + row.id
