import type { AlarmPriorityDisplay } from '@/pages/AlarmSettingsPage/alarmPriorityTypes'

/** WPF 스크린샷 기준 시연용 우선순위 */
export const MOCK_ALARM_PRIORITIES: AlarmPriorityDisplay[] = [
  {
    id: 1,
    priority: 10,
    color: '#ff4444',
    alarmFg: '#ff4444',
    alarmBg: '#1a1a1a',
    alarmBgEnabled: false,
    ackFg: '#888888',
    ackBg: '#1a1a1a',
    ackBgEnabled: false,
    blinking: 'off',
    alarmSound: 'none',
  },
  {
    id: 2,
    priority: 20,
    color: '#ff8844',
    alarmFg: '#ff8844',
    alarmBg: '#1a1a1a',
    alarmBgEnabled: false,
    ackFg: '#888888',
    ackBg: '#1a1a1a',
    ackBgEnabled: false,
    blinking: 'off',
    alarmSound: 'none',
  },
  {
    id: 3,
    priority: 30,
    color: '#ffaa44',
    alarmFg: '#ffaa44',
    alarmBg: '#1a1a1a',
    alarmBgEnabled: false,
    ackFg: '#888888',
    ackBg: '#1a1a1a',
    ackBgEnabled: false,
    blinking: 'off',
    alarmSound: 'none',
  },
  {
    id: 4,
    priority: 40,
    color: '#ffcc00',
    alarmFg: '#ffcc00',
    alarmBg: '#1a1a1a',
    alarmBgEnabled: false,
    ackFg: '#aaaaaa',
    ackBg: '#1a1a1a',
    ackBgEnabled: false,
    blinking: 'off',
    alarmSound: 'none',
  },
  {
    id: 5,
    priority: 50,
    color: '#88cc44',
    alarmFg: '#88cc44',
    alarmBg: '#1a1a1a',
    alarmBgEnabled: false,
    ackFg: '#888888',
    ackBg: '#1a1a1a',
    ackBgEnabled: false,
    blinking: 'off',
    alarmSound: 'none',
  },
  {
    id: 6,
    priority: 60,
    color: '#44cc66',
    alarmFg: '#44cc66',
    alarmBg: '#1a1a1a',
    alarmBgEnabled: false,
    ackFg: '#66aa66',
    ackBg: '#1a1a1a',
    ackBgEnabled: false,
    blinking: 'off',
    alarmSound: 'none',
  },
  {
    id: 7,
    priority: 70,
    color: '#44aacc',
    alarmFg: '#44aacc',
    alarmBg: '#1a1a1a',
    alarmBgEnabled: false,
    ackFg: '#888888',
    ackBg: '#1a1a1a',
    ackBgEnabled: false,
    blinking: 'off',
    alarmSound: 'none',
  },
  {
    id: 8,
    priority: 80,
    color: '#4488ff',
    alarmFg: '#4488ff',
    alarmBg: '#1a1a1a',
    alarmBgEnabled: false,
    ackFg: '#888888',
    ackBg: '#1a1a1a',
    ackBgEnabled: false,
    blinking: 'off',
    alarmSound: 'none',
  },
  {
    id: 9,
    priority: 90,
    color: '#8866ff',
    alarmFg: '#8866ff',
    alarmBg: '#1a1a1a',
    alarmBgEnabled: false,
    ackFg: '#888888',
    ackBg: '#1a1a1a',
    ackBgEnabled: false,
    blinking: 'off',
    alarmSound: 'none',
  },
  {
    id: 10,
    priority: 100,
    color: '#cc66ff',
    alarmFg: '#cc66ff',
    alarmBg: '#1a1a1a',
    alarmBgEnabled: false,
    ackFg: '#aa88cc',
    ackBg: '#1a1a1a',
    ackBgEnabled: false,
    blinking: 'off',
    alarmSound: 'none',
  },
]
