import type { AlarmRuleDisplay } from '@/pages/AlarmSettingsPage/alarmRuleTypes'
import type { ScpInfo } from '@/types/api'

export const MOCK_ALARM_SCPS: ScpInfo[] = [
  {
    id: 1,
    name: 'DGU-TEST-1',
    active: 1,
    connstr: '192.168.1.10:8001',
    model: 4502,
    ctype: 1,
    ext: '',
  },
  {
    id: 2,
    name: 'Adam242',
    active: 1,
    connstr: '192.168.1.20:8001',
    model: 242,
    ctype: 1,
    ext: '',
  },
]

export const MOCK_ALARM_RULES: AlarmRuleDisplay[] = [
  {
    id: 1,
    name: 'ACC-TEST-1',
    active: 1,
    deviceId: 101,
    deviceType: 'reader',
    eventCondition: '',
    eventCode: 'ihs_accel',
    scpId: 1,
    priority: 4,
    monitoring: true,
    ackRequired: false,
    alarmSound: 'none',
    timezone: 'default',
    userIds: [1, 2],
  },
  {
    id: 2,
    name: 'ACC-TEST-2',
    active: 0,
    deviceId: 102,
    deviceType: 'reader',
    eventCondition: '',
    eventCode: 'acc_door',
    scpId: 1,
    priority: 66,
    monitoring: true,
    ackRequired: false,
    alarmSound: 'none',
    timezone: 'default',
    userIds: [1, 3],
  },
  {
    id: 3,
    name: 'Adam All Input Changed',
    active: 1,
    deviceId: 0,
    deviceType: 'input',
    eventCondition: '',
    eventCode: 'adam_input',
    scpId: 2,
    priority: 5,
    monitoring: true,
    ackRequired: false,
    alarmSound: 'none',
    timezone: 'business',
    userIds: [2],
  },
  {
    id: 4,
    name: 'IHS Alert 1',
    active: 1,
    deviceId: 201,
    deviceType: 'input',
    eventCondition: '',
    eventCode: 'ihs_accel',
    scpId: 1,
    priority: 10,
    monitoring: false,
    ackRequired: true,
    alarmSound: 'beep1',
    timezone: 'default',
    userIds: [],
  },
]

export const MOCK_ALARM_USERS = [
  { id: 1, loginId: 'catis', name: 'catis' },
  { id: 2, loginId: 'chchoi', name: 'chchoi' },
  { id: 3, loginId: 'gltest', name: 'gltest' },
  { id: 4, loginId: 'admin', name: 'admin' },
  { id: 5, loginId: 'operator', name: 'operator' },
]
