import { filterPagedByDate } from '@/lib/mock/pagedDateFilter'
import type {
  AccessLogItem,
  AccessLogParams,
  AlarmLogItem,
  AlarmLogParams,
  PagedLogResponse,
} from '@/types/api/eventMonitor'

const forceMock = import.meta.env.VITE_EVENT_HISTORY_MOCK === 'true'

const atOffset = (daysAgo: number, hours: number, minutes: number): string => {
  const d = new Date()
  d.setDate(d.getDate() - daysAgo)
  d.setHours(hours, minutes, 0, 0)
  return d.toISOString()
}

const MOCK_ACCESS_LOG: AccessLogItem[] = [
  {
    id: 1001,
    eventType: 'Card Accepted',
    cardNo: '1234567890',
    empName: '홍길동',
    scpId: 1,
    scpName: 'SCP-01',
    deviceId: 'READER-01',
    deviceName: 'MAIN GATE',
    direction: 'IN',
    occurredAt: atOffset(0, 9, 12),
  },
  {
    id: 1002,
    eventType: 'Card Accepted',
    cardNo: '2345678901',
    empName: '김영희',
    scpId: 1,
    scpName: 'SCP-01',
    deviceId: 'READER-02',
    deviceName: 'SIDE GATE',
    direction: 'OUT',
    occurredAt: atOffset(0, 8, 45),
  },
  {
    id: 1003,
    eventType: 'Card Rejected',
    cardNo: '9876543210',
    empName: '—',
    scpId: 1,
    scpName: 'SCP-01',
    deviceId: 'READER-01',
    deviceName: 'MAIN GATE',
    direction: 'IN',
    occurredAt: atOffset(0, 7, 30),
  },
  {
    id: 1004,
    eventType: 'Card Accepted',
    cardNo: '3456789012',
    empName: '이철수',
    scpId: 2,
    scpName: 'SCP-02',
    deviceId: 'READER-03',
    deviceName: 'LOBBY',
    direction: 'IN',
    occurredAt: atOffset(1, 18, 5),
  },
  {
    id: 1005,
    eventType: 'Card Accepted',
    cardNo: '4567890123',
    empName: '박민수',
    scpId: 2,
    scpName: 'SCP-02',
    deviceId: 'READER-04',
    deviceName: 'PARKING',
    direction: 'OUT',
    occurredAt: atOffset(2, 11, 20),
  },
  {
    id: 1006,
    eventType: 'Card Rejected',
    cardNo: '0000000001',
    empName: '—',
    scpId: 1,
    scpName: 'SCP-01',
    deviceId: 'READER-02',
    deviceName: 'SIDE GATE',
    direction: 'IN',
    occurredAt: atOffset(3, 14, 0),
  },
  {
    id: 1007,
    eventType: 'Card Accepted',
    cardNo: '5678901234',
    empName: '최지연',
    scpId: 1,
    scpName: 'SCP-01',
    deviceId: 'READER-01',
    deviceName: 'MAIN GATE',
    direction: 'IN',
    occurredAt: atOffset(5, 10, 15),
  },
  {
    id: 1008,
    eventType: 'Card Accepted',
    cardNo: '6789012345',
    empName: '정우진',
    scpId: 2,
    scpName: 'SCP-02',
    deviceId: 'READER-03',
    deviceName: 'LOBBY',
    direction: 'OUT',
    occurredAt: atOffset(7, 16, 40),
  },
  {
    id: 1009,
    eventType: 'Card Accepted',
    cardNo: '7890123456',
    empName: '한소희',
    scpId: 1,
    scpName: 'SCP-01',
    deviceId: 'READER-01',
    deviceName: 'MAIN GATE',
    direction: 'OUT',
    occurredAt: atOffset(10, 9, 0),
  },
  {
    id: 1010,
    eventType: 'Card Rejected',
    cardNo: '1111222233',
    empName: '—',
    scpId: 2,
    scpName: 'SCP-02',
    deviceId: 'READER-04',
    deviceName: 'PARKING',
    direction: 'IN',
    occurredAt: atOffset(14, 13, 55),
  },
]

const MOCK_ALARM_LOG: AlarmLogItem[] = [
  {
    id: 2001,
    eventType: 'Door Forced Open',
    cardNo: '',
    empName: '',
    scpId: 1,
    scpName: 'SCP-01',
    deviceId: 'INPUT-03',
    deviceName: 'MAIN GATE READER',
    direction: '',
    occurredAt: atOffset(0, 6, 10),
    acked: false,
  },
  {
    id: 2002,
    eventType: 'Intrusion Detected',
    cardNo: '',
    empName: '',
    scpId: 2,
    scpName: 'DGU-01',
    deviceId: 'ZONE-01',
    deviceName: 'ZONE A',
    direction: '',
    occurredAt: atOffset(0, 5, 0),
    acked: true,
  },
  {
    id: 2003,
    eventType: 'Door Held Open',
    cardNo: '',
    empName: '',
    scpId: 1,
    scpName: 'SCP-01',
    deviceId: 'READER-01',
    deviceName: 'MAIN GATE',
    direction: '',
    occurredAt: atOffset(1, 22, 30),
    acked: false,
  },
  {
    id: 2004,
    eventType: 'ADAM Input Active',
    cardNo: '',
    empName: '',
    scpId: 3,
    scpName: 'ADAM-01',
    deviceId: 'ADAM-01-INPUT-1',
    deviceName: 'INPUT 1',
    direction: '',
    occurredAt: atOffset(2, 15, 45),
    acked: true,
  },
  {
    id: 2005,
    eventType: 'Tamper Alarm',
    cardNo: '',
    empName: '',
    scpId: 1,
    scpName: 'SCP-01',
    deviceId: 'READER-02',
    deviceName: 'SIDE GATE',
    direction: '',
    occurredAt: atOffset(4, 3, 20),
    acked: false,
  },
  {
    id: 2006,
    eventType: 'Fire Alarm',
    cardNo: '',
    empName: '',
    scpId: 2,
    scpName: 'SCP-02',
    deviceId: 'INPUT-05',
    deviceName: 'FIRE SENSOR B1',
    direction: '',
    occurredAt: atOffset(6, 12, 0),
    acked: true,
  },
  {
    id: 2007,
    eventType: 'Door Forced Open',
    cardNo: '',
    empName: '',
    scpId: 1,
    scpName: 'SCP-01',
    deviceId: 'READER-01',
    deviceName: 'MAIN GATE',
    direction: '',
    occurredAt: atOffset(12, 8, 15),
    acked: false,
  },
]

export const shouldUseEventHistoryMock = (
  result: PagedLogResponse<unknown>,
): boolean =>
  forceMock || Boolean(result.apiNotReady) || (import.meta.env.DEV && result.items.length === 0)

export const getMockAccessLog = (params: AccessLogParams): PagedLogResponse<AccessLogItem> =>
  filterPagedByDate(MOCK_ACCESS_LOG, params, (row) => row.occurredAt)

export const getMockAlarmLog = (params: AlarmLogParams): PagedLogResponse<AlarmLogItem> =>
  filterPagedByDate(MOCK_ALARM_LOG, params, (row) => row.occurredAt)
